server:
  servlet:
    context-path: /1807
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 2
        max-active: 50
        max-wait: 3000
    host: 127.0.0.1
    timeout: 5000